# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: jekyll-sample
email: localhost@domain.me
description: > # this means to ignore newlines until "baseurl:"
  A site built by jekyll
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://localhost:4000" # the base hostname & protocol for your site
github_username: butageek
github_repo: "https://github.com/butageek"
linkedin_url: "https://ca.linkedin.com/in/hendryzhou"

# Build settings
sass:
  sass_dir: _sass
markdown: kramdown

excerpt_separator: "<!--excerpt-->"